layaout
js-tasks-ru/htmlcss-20220919_konstantin-shavyrkin pull request #4
Opened 2022-09-27 07:04 UTC by Tr1man

2022-09-27 09:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-27 09:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-27 09:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-27 09:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-27 09:47 UTC, GSemikozov requested changes

2022-09-27 09:47 UTC, GSemikozov commented on components/footer/footer.css
> +footer {
селекторы тегов не используем в БЭМ, здесь должен быть класс

2022-09-27 09:47 UTC, GSemikozov commented on components/footer/footer.css
> +footer p.about{
.footer__description

2022-09-27 09:47 UTC, GSemikozov commented on components/footer/footer.css
> +    margin-left: auto;
не хватает стилей описывающих текст

2022-09-27 09:47 UTC, GSemikozov commented on components/header/header.css
> +.header h1 {
если стили для элемента хедера - то .header__title

2022-09-27 09:47 UTC, GSemikozov commented on components/main/main.css
> +main {
класс

2022-09-28 09:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-28 11:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-28 12:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-30 15:08 UTC, GSemikozov requested changes

2022-09-30 15:08 UTC, GSemikozov commented on components/cards/cards.css
> +.cards__card {
а если захотим использовать карточку в другом контексте?)
лучше тогда 2 отдельных блока - cards + card

2022-09-30 15:08 UTC, GSemikozov commented on components/cards/cards.css
> +.cards__card__body {
.card__body

2022-09-30 15:08 UTC, GSemikozov commented on components/cards/cards.css
> +.cards__card__title {
.card__title

2022-09-30 15:08 UTC, GSemikozov commented on components/container/container.css
> +    max-width: 1440px;
1110

2022-09-30 15:08 UTC, GSemikozov commented on components/footer/footer.css
> +    margin-left: auto;
до сих пор актуально

2022-10-02 20:42 UTC, GSemikozov requested changes

2022-10-02 20:42 UTC, GSemikozov commented on components/cards/cards.css
> +.cards__card {
до сих пор актуально

2022-10-02 20:42 UTC, GSemikozov commented on components/cards/cards.css
> +.cards__card__body {
актуально

2022-10-02 20:42 UTC, GSemikozov commented on components/cards/cards.css
> +.cards__card__title {
актуально

2022-10-02 20:42 UTC, GSemikozov commented on components/container/container.css
> +    max-width: 1440px;
актуально

2022-10-02 20:42 UTC, GSemikozov commented on components/footer/footer.css
> +    margin-left: auto;
актуально

2022-10-03 10:36 UTC, Tr1man commented on components/footer/footer.css
> +footer {
Исправил. Что то не то с git, буду разбираться.

2022-10-03 10:36 UTC, Tr1man commented on components/footer/footer.css
> +footer p.about{
Исправил. Что то не то с git, буду разбираться.

2022-10-03 10:36 UTC, Tr1man commented on components/footer/footer.css
> +    margin-left: auto;
Исправил. Что то не то с git, буду разбираться.

2022-10-03 10:37 UTC, Tr1man commented on components/header/header.css
> +.header h1 {
fix

2022-10-03 10:37 UTC, Tr1man commented on components/main/main.css
> +main {
fix

2022-10-03 10:51 UTC, Tr1man commented
Починил. Не в ту ветку слил мастер и перетер изменения вероятно.
Сейчас должна быть актуальная версия.

2022-10-03 18:31 UTC, GSemikozov approved these changes

2022-10-03 18:31 UTC, merged