Lection 2 histogram
js-tasks-ru/htmlcss-20220919_konstantin-shavyrkin pull request #7
Opened 2022-10-02 19:19 UTC by Tr1man

2022-10-02 19:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-02 20:49 UTC, GSemikozov requested changes

2022-10-02 20:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 185px;
лишнее ограничение

2022-10-02 20:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__total{
отсюда и ниже - для текстовых элементов не хватает стилей описывающих собственно текст

2022-10-02 20:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__button > .linkViewButton{
переопределять фундаментальные стили одних блоков из других категорически нельзя - для этой цели надо создать класс-микс в дамках данного блока, например союственно .histogram__button либо .histogram__link

2022-10-02 20:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    align-items: flex-end;
а вот здесь надо зафиксировать высоту (50px)

2022-10-02 20:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 100%;
а здесь это лишнее (если с сервера придет значение null / undefined а мы при этом покажем 100% - это будет обманом пользователя)

2022-10-03 10:06 UTC, Tr1man commented on 04-lection2/01-histogram/histogram.css
> +    height: 185px;
исправил

2022-10-03 10:09 UTC, Tr1man commented on 04-lection2/01-histogram/histogram.css
> +.histogram__total{
Какого описания?

Там везде стандартный.  
font-size: 16px;
font-style: normal;
font-weight: 400;

кроме histogram__number
там  font-size: 20px;

2022-10-03 10:11 UTC, Tr1man commented on 04-lection2/01-histogram/histogram.css
> +.histogram__button > .linkViewButton{
Исправил

2022-10-03 10:13 UTC, Tr1man commented on 04-lection2/01-histogram/histogram.css
> +    align-items: flex-end;
Ок

2022-10-03 10:15 UTC, Tr1man commented on 04-lection2/01-histogram/histogram.css
> +    height: 100%;
Исправил.

2022-10-03 10:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-03 10:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-03 10:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-03 10:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-03 18:35 UTC, GSemikozov requested changes

2022-10-03 18:35 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__total{
а откуда эти "стандартные" стили мы получаем?

2022-10-03 18:35 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__total{
в общем, речь о том, что это наследуемые свойства, и если не прописать явно, и при этом встроить аккордион в другой блок у которого "стандартные" font-size и пр не очень-то и стандартные - например font-size 14 или 48 - то тогда наш аккордион обретет не очень привлекательный вид)

2022-10-04 05:58 UTC, Tr1man commented on 04-lection2/01-histogram/histogram.css
> +.histogram__total{
Понял исправлю.
Я просто исхожу из концепции что у нас как в  [mui ](https://mui.com/material-ui/customization/typography/) для каждого уровня описана типографика и нужно просто использовать правильный  вид текста. Что бы если мы например делаем версию для слабо видящих, у нас везде увеличился текст.

2022-10-06 17:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-08 15:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__total{
чтобы работало как в mui надо использовать относительные единицы измерения и отдельный универсальный компонент типографика (конкретно для текста)

2022-10-08 15:28 UTC, GSemikozov approved these changes

2022-10-08 15:28 UTC, merged